const productsList = [
  {
    id: 1,
    name: "IPA",
    description: "Tucumán Brew Company",
    type: "beer",
    image: "",
    price: "180",
  },
  {
    id: 2,
    name: "Honey",
    description: "Tucuman Brew Company",
    type: "beer",
    image: "",
    price: "180",
  },
  {
    id: 3,
    name: "Golden Ale",
    description: "Tucuman Brew Company",
    type: "beer",
    image: "",
    price: "180",
  },
  {
    id: 4,
    name: "American Amber Ale",
    description: "Tucuman Brew Company",
    type: "beer",
    image: "",
    price: "180",
  },
  {
    id: 5,
    name: "Scottish",
    description: "Tucuman Brew Company",
    type: "beer",
    image: "",
    price: "180",
  },
  {
    id: 6,
    name: "Red IPA",
    description: "Tucuman Brew Company",
    type: "beer",
    image: "",
    price: "180",
  },
  {
    id: 7,
    name: "Porter",
    description: "Tucuman Brew Company",
    type: "beer",
    image: "",
    price: "180",
  },
  {
    id: 8,
    name: "Orange Pale Ale",
    description: "Tucuman Brew Company",
    type: "beer",
    image: "",
    price: "210",
  },
  {
    id: 9,
    name: "Kolsch",
    description: "Tucuman Brew Company",
    type: "beer",
    image: "",
    price: "210",
  },
  {
    id: 10,
    name: "Simple",
    type: "food",
    description: "6 porciones",
    image: "",
    price: "480",
  },
  {
    id: 11,
    name: "Especial",
    type: "food",
    description: "6 porciones",
    image: "",
    price: "540",
  },
  {
    id: 12,
    name: "Napolitana",
    type: "food",
    description: "6 porciones",
    image: "",
    price: "540",
  },
  {
    id: 13,
    name: "Calabresa",
    type: "food",
    description: "6 porciones",
    image: "",
    price: "540",
  },
  {
    id: 14,
    name: "Ternera",
    type: "food",
    description: "6 porciones",
    image: "",
    price: "580",
  },
  {
    id: 15,
    name: "Fugazzeta",
    type: "food",
    description: "6 porciones",
    image: "",
    price: "580",
  },
  {
    id: 16,
    name: "Yankee",
    type: "food",
    description: "6 porciones",
    image: "",
    price: "580",
  },
  {
    id: 17,
    name: "Fresca",
    type: "food",
    description: "6 porciones",
    image: "",
    price: "540",
  },
  {
    id: 18,
    name: "Clasica",
    type: "food",
    description: "Hamburguesa + porción de papas",
    image: "",
    price: "360",
  },
  {
    id: 19,
    name: "Americana",
    type: "food",
    description: "Hamburguesa + porción de papas",
    image: "",
    price: "400",
  },
  {
    id: 20,
    name: "Mexicana",
    type: "food",
    description: "Hamburguesa + porción de papas",
    image: "",
    price: "400",
  },
  {
    id: 21,
    name: "Italiana",
    type: "food",
    description: "Hamburguesa + porción de papas",
    image: "",
    price: "400",
  },
  {
    id: 22,
    name: "Apostoles",
    type: "drinks",
    description: "Apostoles",
    image: "",
    price: "300",
  },
  {
    id: 23,
    name: "Casa Rosa",
    type: "drinks",
    description: "Casa Rosa",
    image: "",
    price: "300",
  },
  {
    id: 24,
    name: "Bulldog",
    type: "drinks",
    description: "Bulldog",
    image: "",
    price: "300",
  },
  {
    id: 25,
    name: "Vermouth Rosso Pomelo",
    type: "drinks",
    description: "Carpano",
    image: "",
    price: "160",
  },
  {
    id: 26,
    name: "Vermouth Bianco Pomelo",
    type: "drinks",
    description: "Carpano",
    image: "",
    price: "160",
  },
  {
    id: 27,
    name: "Fernet",
    type: "drinks",
    description: "Fernet Branca, Coca Cola",
    image: "",
    price: "220",
  },
  {
    id: 28,
    name: "Nieto Senetier",
    type: "drinks",
    description: "Emilia",
    image: "",
    price: "600",
  },
  {
    id: 29,
    name: "Catena Zapata",
    type: "drinks",
    description: "Nicasia",
    image: "",
    price: "900",
  },
  {
    id: 30,
    name: "Red label",
    type: "drinks",
    description: "Johnnie Walker",
    image: "",
    price: "2000",
  },
];

export default productsList;
